#pragma once

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define VIRTUAL_WIDTH 426
#define VIRTUAL_HEIGHT 240

#define SMALL_FONT_SIZE 8
#define MEDIUM_FONT_SIZE 16
#define LARGE_FONT_SIZE 32

#define SPACESHIP_ACCN 100.0f
#define SPACESHIP_ROTATION_SPEED 200.0f
#define	SPACESHIP_SIZE 20
#define	SPACESHIP_HALF_SIZE 10

#define ASTEROID_MIN_VELOCITY 50
#define ASTEROID_MAX_VELOCITY 100
#define ASTEROID_ROTATION_SPEED 20.0f
#define ASTEROID_SIZE 20


#define BULLET_LIFE_TIME .5f
#define BULLET_VELOCITY 500
#define BULLET_SIZE 2
#define BULLET_HALF_SIZE 1